services:
  # PHP 8.2 service for API endpoints
  php-api:
    image: php:8.2-apache
    container_name: bluesky-php-api
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - bluesky-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/auth.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - node-app

  # Node.js 24 service for Svelte development
  node-app:
    image: node:24-alpine
    container_name: bluesky-node-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - bluesky-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    command: >
      sh -c "
        npm install &&
        npm run dev -- --host 0.0.0.0 --port 5173
      "

networks:
  bluesky-network:
    driver: bridge

volumes:
  app-data:
    driver: local