services:
  bluesky-profile-catcher:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: bluesky-profile-catcher-php
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    volumes:
      # Mount source code for live development
      - .:/var/www/html
      # Optional: Mount a volume for persistent data if needed
      - ./data:/var/www/html/data
    networks:
      - bluesky-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bluesky-network:
    driver: bridge

volumes:
  app-data:
    driver: local