services:
  bluesky-profile-catcher:
    build: .
    container_name: bluesky-profile-catcher
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - ORIGIN=http://localhost:3000
    volumes:
      # Optional: Mount a volume for persistent data if needed
      - ./data:/app/data
    networks:
      - bluesky-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bluesky-network:
    driver: bridge

volumes:
  app-data:
    driver: local